# blogchain.toml is the file that tells build tools (like pip 10+ and build)
# what system you are using and what is required for building.
# The default if this file is missing is to assume a classic setuptools build system,
# but it is better to be explicit; if you have a pyproject.toml file,
# you will be able to rely on wheel and other packages being present.
[metadata]

title = "Blogchain"
version = "0.0.1"
description = "A personal blog"
long_description = "file: README.md"
long_description_content_type = "text/markdown"

packages="setuptools.find_packages(where='flaskr')",
python_requires=">=3.6",
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
url = "" # TODO add in once github repo created
[metadata.project-urls]
bug_tracker = "" # TODO add in once github repo created

[owner]
name = "Derek Wayne"
dob = 1989-07-27T07:32:00-08:00
email = "derekwayne4@gmail.com"

[options]
package_dir={"": "flaskr"}
packages = "find:"
python_requires = ">=3.7"

[options.packages.find]
where = "flaskr"


# [database]
# enabled = true
# ports = [ 8000, 8001, 8002 ]
# data = [ ["delta", "phi"], [3.14] ]
# temp_targets = { cpu = 79.5, case = 72.0 }

# [servers]

# [servers.alpha]
# ip = "10.0.0.1"
# role = "frontend"

# [servers.beta]
# ip = "10.0.0.2"
# role = "backend"

